server:
  port: 9200
  servlet:
    context-path: /identity


spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: Kuluan12@
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true